### PR TITLE
Prevent the installation of MiniConda to register on Windows

### PR DESCRIPTION
**Pull request by RoyiAvital**
See https://github.com/heetbeet/juliawin/issues/45 and https://github.com/JuliaPy/Conda.jl/issues/147.

### CODE REVIEW

**Comment by RoyiAvital** [comment]
@stevengj , Have you had the chance to look at this?

**Comment by stevengj** [comment]
LGTM, thanks.

**Comment by RoyiAvital** [comment]
@stevengj , Any chance releasing a version with this so the Portable version will work?

**Comment by RoyiAvital** [comment]
@stevengj , Could you please tag a new version with this fix before `1.6.1`?
It will be useful for the Portable Distribution.

Thank You.

**Pull request merged**
