### PR TITLE
Test on LTS and x86

### PR DESCRIPTION
**Pull request by davidanthoff**

### CODE REVIEW

**Comment by stevengj** [comment]
The CI failures here are not regressions, I guess?

**Comment by mkitti** [comment]
There is no miniforge support for x86:
https://github.com/conda-forge/miniforge

The last support for miniconda is Python 3.9:
https://docs.conda.io/en/latest/miniconda.html

Python 3.9 is supported through October 2025:
https://devguide.python.org/versions/

**Comment by mkitti** [comment]
Could we merge the 1.6 (LTS) testing without x86?

**Comment by ViralBShah** [comment]
Trying to simplify to a smaller set and refresh the CI script here. Hoping to merge this and then get more platforms etc. in later.

**Comment by ViralBShah** [comment]
#259 should hopefully pull in a new enough version of numpy that it is available on arm macs.

**Pull request merged**
