### PR TITLE
Single '='  instead of "=="

### PR DESCRIPTION
**Pull request by lilinjn**
I believe this was a small typo

### CODE REVIEW

**Comment by isuruf** [comment]
This is a breaking change though. 

Two packages using the syntax `==`
https://github.com/symengine/SymEngine.jl
https://github.com/wkearn/RasterIO.jl

**Comment by lilinjn** [comment]
hmm -- I will rewrite it to support both versions.  How did you find those two packages so quickly?

**Comment by isuruf** [comment]
:+1: 
First one is a package I'm a contribute to and the second one from a simple github search. https://github.com/search?l=julia&p=2&q=Conda&type=Code&utf8=%E2%9C%93

**Comment by Luthaf** [comment]
Both `package=<version>` and `package ==<version>` are [supported by conda](http://conda.pydata.org/docs/spec.html#examples), so it would be better if we could support both too.

**Comment by lilinjn** [comment]
Hi  - I soon realized that this method searches the global Conda database (I had mistakenly wanted to use it to search locally installed packages).  It seems the best fix would be to fully support the full version semantics of `search` (e.g. `>=` etc), which would require thinking a bit about what the proper solution would be.  I'm going to close this and revisit this later.

**Pull request closed without merging**
