### PR TITLE
rename condarc-julia to condarc-julia.yml

### PR DESCRIPTION
**Pull request by tkelman**
avoid a new assertion
```
Traceback (most recent call last):
  File "/Users/travis/.julia/v0.4/Conda/deps/usr/bin/conda", line 4, in <module>
    import conda.cli
  File "/Users/travis/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/conda/cli/__init__.py", line 8, in <module>
    from .main import main  # NOQA
  File "/Users/travis/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/conda/cli/main.py", line 46, in <module>
    from ..base.context import context
  File "/Users/travis/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/conda/base/context.py", line 251, in <module>
    context = Context(SEARCH_PATH, conda, None)
  File "/Users/travis/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/conda/common/configuration.py", line 692, in __init__
    self._add_search_path(search_path)
  File "/Users/travis/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/conda/common/configuration.py", line 699, in _add_search_path
    return self._add_raw_data(load_file_configs(search_path))
  File "/Users/travis/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/conda/common/configuration.py", line 371, in load_file_configs
    raw_data = odict(kv for kv in chain.from_iterable(load_paths))
  File "/Users/travis/.julia/v0.4/Conda/deps/usr/lib/python2.7/collections.py", line 69, in __init__
    self.__update(*args, **kwds)
  File "/Users/travis/.julia/v0.4/Conda/deps/usr/lib/python2.7/_abcoll.py", line 571, in update
    for key, value in other:
  File "/Users/travis/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/conda/common/configuration.py", line 371, in <genexpr>
    raw_data = odict(kv for kv in chain.from_iterable(load_paths))
  File "/Users/travis/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/conda/common/configuration.py", line 346, in _file_yaml_loader
    assert fullpath.endswith(".yml") or fullpath.endswith("condarc"), fullpath
AssertionError: /Users/travis/.julia/v0.4/Conda/deps/usr/condarc-julia
```

### CODE REVIEW

**Comment by tkelman** [comment]
One error down, now we're hitting
```
Unlinking packages ...
[      COMPLETE      ]|###################################################| 100%
Warning: 'foo' already in 'channels' list, moving to the top
Warning: 'defaults' already in 'channels' list, moving to the top
ERROR: LoadError: BoundsError: attempt to access 1-element Array{SubString{ASCIIString},1}:
 "@EXPLICIT"
  at index [2]
 in getindex at ./array.jl:283
 in indexed_next at tuple.jl:22
 in _installed_packages_dict at /home/travis/.julia/v0.4/Conda/src/Conda.jl:170
 in _installed_packages at /home/travis/.julia/v0.4/Conda/src/Conda.jl:186
 in teardown at /home/travis/.julia/v0.4/Conda/test/runtests.jl:32
 in main at /home/travis/.julia/v0.4/Conda/test/runtests.jl:81
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 in process_options at ./client.jl:280
 in _start at ./client.jl:378
while loading /home/travis/.julia/v0.4/Conda/test/runtests.jl, in expression starting on line 84
```

@stevengj @Luthaf any ideas? Everything using Conda.jl has started failing with the release of Conda 4.2.6. http://pkg.julialang.org/pulse.html

**Comment by tkelman** [comment]
Looks like `conda list --export` was broken by https://github.com/conda/conda/pull/3291/files#r79096929

**Comment by tkelman** [comment]
This seems to work so if I don't hear otherwise I think I'm going to merge and tag this just to get things working again. Depending what happens upstream with `list --export` we may go back to the old way.

**Comment by tkelman** [comment]
@dhoegh looks like you changed this in #28. Given `--export` was broken upstream, do you think splitting the normal `conda list` output on whitespace will be any better or worse than `--json` ?

**Comment by tkelman** [comment]
Looks like I may need to backport this to a version of Conda.jl that supports Julia 0.3 and make a metadata freeze exception, unless it gets resolved upstream in a way that won't go away again.

**Comment by dhoegh** [comment]
The main reason for choosing `--export` was the seperation with "=" as I was unsure whether Conda allowed spaces in package names.

**Comment by tkelman** [comment]
Might come back upstream for the time being? Not sure when https://github.com/conda/conda/pull/3450 will make it out to releases.

**Comment by tkelman** [comment]
Looks like space-separated won't entirely work for things from channels, e.g. @Luthaf's chemfiles:
```
CondaValueError: Value error: invalid package specification: chemfiles-lib             0.6.0                         0    luthaf


ERROR: LoadError: failed process: Process(setenv(`/home/vagrant/.julia/v0.5/Conda/deps/usr/bin/conda install -y 'chemfiles-lib             0.6.0                         0    luthaf'`,String["PYTHON=","PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/vagrant/julia/bin/","PWD=/vagrant/0.5AL","SHELL=/bin/bash","SSH_CONNECTION=10.0.2.2 39353 10.0.2.15 22","LD_LIBRARY_PATH=:/usr/local/lib/","CONDARC=/home/vagrant/.julia/v0.5/Conda/deps/usr/condarc-julia.yml","MAIL=/var/mail/vagrant","LANG=en_US.UTF-8","SHLVL=4","LOGNAME=vagrant","XDG_RUNTIME_DIR=/run/user/1000","XDG_SESSION_ID=3","SSH_CLIENT=10.0.2.2 39353 22","_=/usr/bin/timeout","USER=vagrant","TERM=vt100","HOME=/home/vagrant","OPENBLAS_MAIN_FREE=1","JAVA_HOME=/usr/lib/jvm/java-7-oracle"]), ProcessExited(1)) [1]
 in pipeline_error(::Base.Process) at ./process.jl:616
 in run(::Cmd) at ./process.jl:592
 in add(::String) at /home/vagrant/.julia/v0.5/Conda/src/Conda.jl:146
 in teardown() at /home/vagrant/.julia/v0.5/Conda/test/runtests.jl:36
 in main() at /home/vagrant/.julia/v0.5/Conda/test/runtests.jl:81
 in include_from_node1(::String) at ./loading.jl:488
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318
while loading /home/vagrant/.julia/v0.5/Conda/test/runtests.jl, in expression starting on line 84
```

Might revert the second commit given conda 4.2.7 has a hotfix.

**Pull request merged**
