### PR TITLE
move BinDeps support to a separate package

### PR DESCRIPTION
**Pull request by stevengj**
This is useful since most of the Conda users don't seem to use BinDeps anymore.

A CondaBinDeps.jl package ~~will be created shortly.~~ is here: https://github.com/JuliaPackaging/CondaBinDeps.jl

Don't merge this PR until CondaBinDeps is working and tagged in metadata, so that people using Conda can upgrade — i.e. wait for JuliaLang/METADATA.jl#15942

### CODE REVIEW

**Comment by stevengj** [comment]
The only registered packages that seem to use the Conda BinDeps feature are: NCDatasets, NetCDF, UDUnits

**Comment by isuruf** [comment]
Also Chemfiles, SymEngine

**Comment by stevengj** [comment]
Chemfiles doesn't use Conda.jl, but good catch on SymEngine.

**Comment by stevengj** [comment]
Okay, looks ready to merge since all of the dependencies have been updated.

**Pull request merged**
